#!/bin/bash

rm -fv ./combined_*
rm -fv cimage.pbs.e*
rm -fv cimage.pbs.o*

if [ -d dta ]; then
	cd dta
	rm -fv cross_scan.table
	rm -fv cimageOut.txt
	rm -fv all_scan.table
	rm -fv ipi_name.table
	rm -fv findMs1AcrossSetsFromDTASelect.Rout
	rm -fv ./*.txt.tagged
	rm -fv ./*.txt.tmp*
    rm -fv ./*.tmp.scan
	rm -fv ./tmp.*	
	rm -rf Rplots.pdf
	echo "Removing output..."
	rm -rf output
	echo "Done!"
fi


